name: Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build
        run: |
          .\install_certs.bat
          .\build.bat

      - name: List coverage files
        shell: bash
        run: |
          echo "Searching for JaCoCo files..."
          find . -name "*jacoco*"

      - name: Collect jacoco XML reports
        id: collect
        shell: cmd
        run: |
          setlocal EnableDelayedExpansion
          cd /d "%GITHUB_WORKSPACE%"
          echo Searching for jacoco.xml files...
          set "FILES="

          for /f "delims=" %%F in ('dir /s /b jacoco.xml 2^>nul') do (
              echo Found: %%F
              set "FILES=!FILES! %%F"
          )

          set "FILES=!FILES:~1!"
          set "FILES=!FILES:\=/%!"

          echo files=!FILES!>>"%GITHUB_OUTPUT%"

          echo Final file list:
          echo !FILES!

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ${{ steps.collect.outputs.files }}
          verbose: true
          fail_ci_if_error: true
